//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 DiskMonitor.rc 使用
//
#define IDT_CONFIG_GETDISKSPEED         1
#define IDS_DISKTYPE_HDD                1000
#define IDC_GROUP_ALLDISKINFO           1000
#define IDT_CONFIG_GETDISKSPEED_INTERVAL 1000
#define IDS_DISKTYPE_SSD                1001
#define IDD_CONFIG_DIALOG               1001
#define IDC_GROUP_MONITOREDDISKINFO     1001
#define IDS_DISKTYPE_SCM                1002
#define IDS_DISKTYPE_LOGICAL            1003
#define IDC_LIST_MONITOREDDISKINFO      1003
#define IDR_MENU_DISKINFO               1003
#define IDS_DISKTYPE_UNKNOWN            1004
#define IDC_LIST_ALLDISKINFO            1004
#define IDS_DEFAULT_LOGICAL_DISK_CAPTION 1005
#define IDC_GROUP_OPERATIONS            1005
#define IDS_GETDISKINFO_ERROR           1006
#define IDC_BTN_ALLDISK_REFRESH         1006
#define IDS_GETPHYSICALDISK_ERROR       1007
#define IDC_BTN_ALLDISK_ADDTOMONITORED  1007
#define IDS_GETERRORSTRING_ERROR        1008
#define IDC_BTN_MONITOREDDISK_DELETE    1008
#define IDS_LISTCOLUMN_ID               1009
#define IDC_BTN_MONITOREDDISK_CLEAR     1009
#define IDS_LISTCOLUMN_CAPTION          1010
#define IDC_GROUP_EXAMPLE               1010
#define IDS_LISTCOLUMN_DISKTYPE         1011
#define IDS_LISTCOLUMN_SIZE             1012
#define IDC_TEXT_SPEED_READ             1012
#define IDS_LISTCOLUMN_DEVICEID         1013
#define IDC_TEXT_SPEED_WRITE            1013
#define IDS_CONFIG_ALLDISK_REFRESHED    1014
#define IDS_CONFIG_DISKID_CONFLICT      1015
#define IDC_GROUP_EDITPREFIX            1015
#define IDS_CONFIG_DISKDEVICE_CONFLICT  1016
#define IDC_TEXT_EDITPREFIX_READ        1016
#define IDS_CONFIG_DISKTYPE_UNKNOWN     1017
#define IDC_EDIT_EDITPREFIX_READ        1017
#define IDS_CONFIG_CONFIRM_CLEAR_MONITORED 1018
#define IDC_TEXT_EDITPREFIX_WRITE       1018
#define IDS_CONFIG_EXAMPLE_READ         1019
#define IDC_EDIT_EDITPREFIX_WRITE       1019
#define IDS_CONFIG_EXAMPLE_WRITE        1020
#define IDS_GET_DISKSPEED_ERROR         1021
#define IDS_PLUGIN_NAME                 1022
#define IDS_PLUGIN_DESCRIPTION          1023
#define IDS_PLUGIN_AUTHOR               1024
#define IDS_PLUGIN_COPYRIGHT            1025
#define IDS_PLUGIN_VERSION              1026
#define IDS_PLUGIN_URL                  1027
#define IDS_PLUGIN_MONITORING_DISKS     1028
#define IDS_PLUGIN_TOTAL_DISKIO         1029
#define IDS_ASSERT_FAIL                 1030
#define ID_ALLDISK_32771                32771
#define ID_ALLDISK_32772                32772
#define ID_MONITOREDDISK_32773          32773
#define ID_MONITOREDDISK_32774          32774
#define IDR_ALLDISK_ADDTOMONITOR        32775
#define IDR_ALLDISK_REFRESH             32776
#define IDR_MONITOREDDISK_DELETE        32777
#define IDR_MONITOREDDISK_CLEAR         32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1004
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           1002
#endif
#endif
